name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Se ejecutará cada vez que subas algo a main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package-lock.json # Ajustado porque tu código está en la carpeta /app

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build
        run: npm run build
        working-directory: ./app

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './app/dist' # Carpeta donde Vite genera la web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
